workflows:
  ios_testflight:
    name: iOS TestFlight (Flutter)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: com.yourco.hmepod
        XCODE_WORKSPACE: ios/Runner.xcworkspace
        XCODE_SCHEME: Runner
      groups:
        - app_store_credentials   # must include: APP_STORE_CONNECT_* , APPLE_TEAM_ID , (NO CERTIFICATE_PRIVATE_KEY here)

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Flutter build iOS (no codesign)
        script: flutter build ios --release --no-codesign

      - name: CocoaPods install
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Import distribution P12 and fetch profiles
        script: |
          # Sanity checks
          if [ -z "${DISTRIBUTION_P12_BASE64:-}" ]; then
            echo "ERROR: DISTRIBUTION_P12_BASE64 is empty"; exit 2
          fi
          if [ -z "${DISTRIBUTION_P12_PASSWORD:-}" ]; then
            echo "ERROR: DISTRIBUTION_P12_PASSWORD is empty"; exit 2
          fi

          # 1) Materialize the base64 P12 into a file
          CERT_DIR="$HOME/Library/MobileDevice/Certificates"
          mkdir -p "$CERT_DIR"
          python3 -c "import os,base64,sys,pathlib;
p=pathlib.Path(os.environ['HOME'])/'Library/MobileDevice/Certificates'/'env_cert.p12';
p.write_bytes(base64.b64decode(os.environ['DISTRIBUTION_P12_BASE64'].strip().encode()));
print(p)"

          # 2) Initialize keychain & import the P12 with password
          keychain initialize
          keychain add-certificates \
            --certificate "$CERT_DIR/env_cert.p12" \
            --certificate-password "$DISTRIBUTION_P12_PASSWORD"

          # 3) Fetch/create provisioning profiles for this bundle id
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create

          # 4) Apply profiles to the Xcode project (this CLI expects --project)
          xcode-project use-profiles --project ios/Runner.xcodeproj

      - name: Show signing settings
        script: |
          xcode-project show-build-settings \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
          | grep -E "PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM|PROVISIONING_PROFILE_SPECIFIER|CODE_SIGN_STYLE"

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-method app-store

      - name: Publish to TestFlight
        script: |
          app-store-connect publish \
            --path "build/ios/ipa/*.ipa" \
            --submit-to-testflight true \
            --release-type MANUAL

    artifacts:
      - build/ios/ipa/*.ipa
