workflows:
  ios_testflight:
    name: iOS → TestFlight (Flutter)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: com.yourco.hmepod
        XCODE_WORKSPACE: ios/Runner.xcworkspace
        XCODE_SCHEME: Runner
      groups:
        - app_store_credentials   # contains APP_STORE_CONNECT_* vars

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: CocoaPods install
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: (one-time) Create Apple Distribution cert if missing
        script: |
          if [ -z "${CERTIFICATE_PRIVATE_KEY:-}" ]; then
            echo "Creating Apple Distribution certificate..."
            app-store-connect certificates create \
              --type IOS_DISTRIBUTION \
              --save-private-key CERTIFICATE_PRIVATE_KEY
            echo "----- COPY EVERYTHING BELOW into a Secure env var named CERTIFICATE_PRIVATE_KEY -----"
            echo "$CERTIFICATE_PRIVATE_KEY"
            echo "----- END COPY -----"
            exit 1
          else
            echo "CERTIFICATE_PRIVATE_KEY already set; skipping creation."
          fi


      - name: Fetch & install signing (automatic)
        script: |
          app-store-connect fetch-signing-files \
            --type IOS_APP_STORE \
            --bundle-id "$BUNDLE_ID" \
            --create
          ls -al "$HOME/Library/MobileDevice/Certificates" || true
          ls -al "$HOME/Library/MobileDevice/Provisioning Profiles" || true
          keychain initialize
          keychain add-certificates || true
          CERT_DIR="$HOME/Library/MobileDevice/Certificates"
          if [ -z "$(ls -1 "$CERT_DIR"/*.p12 2>/dev/null)" ]; then
            echo "ERROR: No .p12 certificates were created/fetched. Check API key role/team/quota."
            exit 2
          fi
          xcode-project use-profiles \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

      - name: Publish to TestFlight
        script: |
          app-store-connect publish \
            --path "build/ios/ipa/*.ipa" \
            --submit-to-testflight true \
            --release-type MANUAL

    artifacts:
      - build/ios/ipa/*.ipa
