workflows:
  ios_testflight:
    name: iOS → TestFlight (Flutter)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: com.yourco.hmepod
        XCODE_WORKSPACE: ios/Runner.xcworkspace
        XCODE_SCHEME: Runner
      groups:
        - app_store_credentials   # contains: APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY, APPLE_TEAM_ID

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: CocoaPods clean & install
        script: |
          cd ios
          rm -f Podfile.lock
          pod repo update
          pod install
          cd ..

      - name: (one-time) Create Apple Distribution cert if missing
        script: |
          if [ -z "${CERTIFICATE_PRIVATE_KEY:-}" ]; then
            echo "No CERTIFICATE_PRIVATE_KEY set; creating a new Apple Distribution certificate..."
            app-store-connect certificates create --type IOS_DISTRIBUTION --save-private-key CERTIFICATE_PRIVATE_KEY
            echo "----- COPY EVERYTHING BELOW into a Secure env var named CERTIFICATE_PRIVATE_KEY -----"
            echo "$CERTIFICATE_PRIVATE_KEY"
            echo "----- END COPY -----"
          else
            echo "CERTIFICATE_PRIVATE_KEY already present; skipping cert creation."
          fi

      - name: Fetch signing files & apply
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles --project ios/Runner.xcodeproj --scheme "$XCODE_SCHEME"

      # Single step: archive + export IPA
      - name: Build & Export IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-method app-store

      - name: Publish to TestFlight
        script: |
          app-store-connect publish \
            --path "build/ios/ipa/*.ipa" \
            --submit-to-testflight true \
            --release-type MANUAL




    artifacts:
