workflows:
  ios_testflight:
    name: iOS → TestFlight (Flutter)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      vars:                        # <-- moved here
        BUNDLE_ID: com.yourco.hmepod
        XCODE_WORKSPACE: ios/Runner.xcworkspace
        XCODE_SCHEME: Runner
      groups:                      # <-- moved here
        - app_store_credentials    # (the env group you created with the 4 Apple vars)

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: CocoaPods clean & install
        script: |
          cd ios
          rm -f Podfile.lock
          pod repo update
          pod install
          cd ..

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"

      - name: Build archive
        script: |
          rm -rf build/ios/xcarchive
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -archivePath build/ios/xcarchive/Runner.xcarchive \
                     archive \
                     CODE_SIGN_STYLE=Manual \
                     COMPILER_INDEX_STORE_ENABLE=NO

      - name: Export IPA
        script: |
          xcode-project export-ipa \
            --archive build/ios/xcarchive/Runner.xcarchive \
            --export-method app-store \
            --output build/ios/ipa

      - name: Publish to TestFlight
        script: |
          app-store-connect publish \
            --path "build/ios/ipa/*.ipa" \
            --submit-to-testflight true \
            --release-type MANUAL

    artifacts:
      - build/ios/ipa/*.ipa
